### ISSUE TITLE
BaristaCore 1.0.2-beta03 does not work BaristaCore.ChakraCore 1.10.2

### ISSUE THREAD

**Issue by johlrich** [BaristaLabs/BaristaCore#66]
I initially had a hard time getting started b/c if an unhandled exception `BaristaLabs.BaristaCore.JsScriptException: fetch import module failed`. Here's the references used in a fresh console app:

    <PackageReference Include="BaristaCore" Version="1.0.2-beta03" />
    <PackageReference Include="BaristaLabs.BaristaCore.ChakraCore" Version="1.10.2" />

After pinning to 1.8.1, everything worked just fine. I then built from source and everything worked with the 1.10.2 version, so my best guess is BaristaCore/Extensions may need a newer publish to match ChakraCore, but I didn't look any further.

Besides this initial minor bump, I'm having a lot of fun experimenting with it this weekend; I'm really glad I stumbled across it. Thanks for sharing!

**Comment by Oceanswave** [comment]
Thanks for trying it out!

Yeah, I'm currently in the middle of updating to 1.10.x which located in [this branch](https://github.com/BaristaLabs/BaristaCore/tree/improve-code-coverage) but haven't gotten the cycles to resolve one or two remaining issues (#60 et. al.)

Let me know if there's any improvements I can make and what you think in general.

**Comment by Oceanswave** [comment]
BaristaCore 1.0.3-beta01 has been published which specifies the 1.10.2 version of ChakraCore https://www.nuget.org/packages/BaristaCore/1.0.3-beta01

Thanks,
